export {default as main_logo} from "./BullSmartLogo.png"
export {default as hero_img} from "./hero_img.gif"
export {default as your_money_img} from "./your_money.gif"
export {default as learn1_img} from "./learn1.webp"
export {default as learn2_img} from "./learn2.webp"
export {default as learn3_img} from "./learn3.webp"